export const USER_LOGIN_START = "USER_LOGIN_START"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
export const USER_LOGOUT = "USER_LOGOUT"

export const SET_ERROR_REQ = "SET_ERROR_REQ"

export const HANDLE_ROUTE_CHANGE = "HANDLE_ROUTE_CHANGE"